name: Update copyright year in license file

on:
  schedule:
    - cron: '0 6 1 1 *'
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - uses: FantasticFiasco/action-update-license-year@v3
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
      id: license

    - name: Merge PR
      if: steps.license.outputs.pullRequestNumber != ''
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: gh pr merge --squash --delete-branch ${{ steps.license.outputs.pullRequestNumber }}
      with:
        prTitle: 'chore: Updated LICENSE ${{ steps.license.outputs.currentYear }} [skip ci]'
        commitTitle: 'chore: Updated LICENSE ${{ steps.license.outputs.currentYear }}'
